[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = []

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && python3 -m uvicorn main_v2:app --host 0.0.0.0 --port $PORT"
